"""领域层（T1.4 起）：枚举、状态机、Pydantic 契约、任务状态唯一写入口。

分层（``core -> db -> domain -> services -> pools/pipeline -> app``）
-----------------------------------------------------------------
本包只依赖 ``core`` 与 ``db``，**不导入** ``services`` / ``pools`` / ``app``。

模块归属
--------
- ``enums.py``         16 态 ``TaskStatus`` 等枚举（DDL CHECK 的 Python 镜像）
- ``errors.py``        ``IllegalTransition`` / ``ConcurrentModification`` / ``TaskNotFound``
- ``state_machine.py`` ``ALLOWED_TRANSITIONS`` 16×16 迁移矩阵（纯函数，无 I/O）
- ``models.py``        ``TaskRead`` / ``TaskPayload`` / ``QualityReport`` / ``TaskEventRead``
- ``task_service.py``  ★ ``tasks`` 表的**唯一写入口**
- ``topics.py``        T1.9 选题领域（归一化/哈希/相似度/四规则/两级去重/分类契约）
- ``text.py``          T1.10 口播文本工具（口播字数 / 分句 / 超长句切分）
- ``script.py``        T1.10 写稿契约（Director 大纲 / Writer 成稿 / 三道闸门）
- ``scoring.py``       T1.11 审稿评分契约（规则通道 / 六维度 / 分级放行 / 改稿越界）
"""

from __future__ import annotations

from studio.domain.enums import (
    ApprovalDecision,
    AutoApprovePolicy,
    Grade,
    JobStatus,
    PoolName,
    PublishStatus,
    TaskKind,
    TaskPool,
    TaskStatus,
    UnitType,
)
from studio.domain.errors import ConcurrentModification, IllegalTransition, TaskNotFound
from studio.domain.models import QualityReport, TaskEventRead, TaskPayload, TaskRead
from studio.domain.scoring import (
    DUP_PENALTY,
    DUP_RATIO_MAX,
    EDIT_RETRIES,
    GRADE_A_MIN,
    GRADE_B_MIN,
    LLM_DIMENSIONS,
    LLM_WEIGHT,
    REVISION_LIMIT,
    RULE_WEIGHT,
    BannedHit,
    ChannelItem,
    Decision,
    EditorInput,
    EditorOutput,
    EditReport,
    GateAction,
    LlmChannelDetail,
    ReviewerInput,
    ReviewerOutput,
    ReviewIssue,
    ReviewOutput,
    RuleChannelDetail,
    allowed_sentences,
    auto_approved_by,
    check_edit,
    compute_score,
    decision_for,
    evaluate_rule_channel,
    gate_action,
    llm_total_of,
    paragraph_dup_ratio,
    rule_total_of,
    verdict_for,
)
from studio.domain.script import (
    CATCHPHRASE_MIN_HITS,
    SENTENCE_MAX_CHARS,
    SPEAKER_RATIO_MAX,
    WORD_COUNT_MAX,
    WORD_COUNT_MIN,
    DirectorInput,
    DirectorOutput,
    OutlineReport,
    ScriptDraft,
    ScriptReport,
    ScriptRules,
    ScriptSegment,
    SentenceSpec,
    WriterInput,
    WriterOutput,
    build_draft,
    check_outline,
    check_script,
    enforce_sentence_limit,
)
from studio.domain.state_machine import (
    ALLOWED_TRANSITIONS,
    RESCUE_STATUSES,
    RETRY_FROM_WHITELIST,
    RETRY_SOURCES,
    TERMINAL_STATUSES,
    allowed_targets,
    assert_allowed,
    is_allowed,
)
from studio.domain.task_service import TaskService, TransitionResult

__all__ = [
    "ALLOWED_TRANSITIONS",
    "CATCHPHRASE_MIN_HITS",
    "DUP_PENALTY",
    "DUP_RATIO_MAX",
    "EDIT_RETRIES",
    "GRADE_A_MIN",
    "GRADE_B_MIN",
    "LLM_DIMENSIONS",
    "LLM_WEIGHT",
    "RESCUE_STATUSES",
    "RETRY_FROM_WHITELIST",
    "RETRY_SOURCES",
    "REVISION_LIMIT",
    "RULE_WEIGHT",
    "SENTENCE_MAX_CHARS",
    "SPEAKER_RATIO_MAX",
    "TERMINAL_STATUSES",
    "WORD_COUNT_MAX",
    "WORD_COUNT_MIN",
    "ApprovalDecision",
    "AutoApprovePolicy",
    "BannedHit",
    "ChannelItem",
    "ConcurrentModification",
    "Decision",
    "DirectorInput",
    "DirectorOutput",
    "EditReport",
    "EditorInput",
    "EditorOutput",
    "GateAction",
    "Grade",
    "IllegalTransition",
    "JobStatus",
    "LlmChannelDetail",
    "OutlineReport",
    "PoolName",
    "PublishStatus",
    "QualityReport",
    "ReviewIssue",
    "ReviewOutput",
    "ReviewerInput",
    "ReviewerOutput",
    "RuleChannelDetail",
    "ScriptDraft",
    "ScriptReport",
    "ScriptRules",
    "ScriptSegment",
    "SentenceSpec",
    "TaskEventRead",
    "TaskKind",
    "TaskNotFound",
    "TaskPayload",
    "TaskPool",
    "TaskRead",
    "TaskService",
    "TaskStatus",
    "TransitionResult",
    "UnitType",
    "WriterInput",
    "WriterOutput",
    "allowed_sentences",
    "allowed_targets",
    "assert_allowed",
    "auto_approved_by",
    "build_draft",
    "check_edit",
    "check_outline",
    "check_script",
    "compute_score",
    "decision_for",
    "enforce_sentence_limit",
    "evaluate_rule_channel",
    "gate_action",
    "is_allowed",
    "llm_total_of",
    "paragraph_dup_ratio",
    "rule_total_of",
    "verdict_for",
]
